### ISSUE TITLE
Free has lost (optional) checks for API misuse

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/snmalloc#118]
We used to have a (conditionally compiled) check in the implementation of `free` that the argument to the function was the start of an allocation.  We appear to have lost it and it is important for avoiding some vulnerabilities in a CHERI system: CTSRD-CHERI/cheribsd#342

**Comment by mjp41** [comment]
So on the small dealloc path it is here:
https://github.com/microsoft/snmalloc/blob/4212ac8e4ed134f821ebe2906bdb46ba3142c943/src/mem/alloc.h#L1039-L1045

On the medium dealloc path it is here:
https://github.com/microsoft/snmalloc/blob/4212ac8e4ed134f821ebe2906bdb46ba3142c943/src/mem/alloc.h#L1196-L1203

And on the large dealloc path it is here:
https://github.com/microsoft/snmalloc/blob/4212ac8e4ed134f821ebe2906bdb46ba3142c943/src/mem/alloc.h#L342-L348

Are there paths that are missing?  Pushing it into the code to where we know the size approximately allows for much more efficient checks.

**Comment by davidchisnall** [comment]
Aha!  I was looking in the callers of those.  Sorry for the noise.
