### ISSUE TITLE
memcpy of a non-trivial class lead to compile error on GCC 9.0

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#133]
In a pr to `snmalloc-rs`, we can spot that on `GCC>=8` the `-Wclass-memaccess` will lead to an compilation error.
A possible workaround is:
```c++
#if !defined(__clang__) && defined(__GNUC__)
#if __GNUC__ >= 8
#define GCC_WARNING_ADJUST
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wclass-memaccess"
#endif
#endif
      memcpy(allocated, &local, sizeof(MemoryProviderStateMixin<PAL>));
#ifdef GCC_WARNING_ADJUST
#pragma GCC diagnostic pop
#undef GCC_WARNING_ADJUST
#endif
```
Since we are using `-Werror`, if we do not filter `clang` and lower versions of GCC, `-Wclass-memaccess` will not be recognized and lead to another error.

**Comment by mjp41** [comment]
Thanks for spotting this, I have submitted a PR #134 addressing this as you suggested.
