### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#136]
Currently, the project does not support `MinGW`.
With the following changes, it can compile with `MinGW`:
1. `CmakeLists.txt`: at about line 74, add a branch `AMD64` (quite strange but 'amd64' does not work).
2. `pal_windows.h`:  add some macros
    ```c++
    #  ifndef _MSC_VER
    #  include <cstdio>
    #  endif
    #  ifndef NOMINMAX
    #  define NOMIXMAX
    #  endif
    ``` 
3. `test/usage.h`
```
    #  ifndef NOMINMAX
    #  define NOMIXMAX
    #  endif
```

The project compiles but all test fails. Is there any plan to improve the support?

**Comment by SchrodingerZhu** [comment]
with `Release` profile, I run into another error: 
```
allostats.h: arrat subscript 36 is above bounds of 'snmalloc::AllocStats<59, 28>::Stats [28]'
```

**Comment by mjp41** [comment]
Thanks for pointing this out.  We don't have plans to add support for MinGW, but I am happy to review patches, and take an additional CI process to maintain it.

**Comment by SchrodingerZhu** [comment]
I think I have made it to work with some small changes. PR will be opened soon.

**Comment by SchrodingerZhu** [comment]
#137 provides a possible fix
