### ISSUE TITLE
arm build is still broken

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#144]
https://travis-ci.com/github/SchrodingerZhu/snmalloc-rs/jobs/299253870

**Comment by mjp41** [comment]
Thanks, @schrodingerzhu we have been looking at adding some Arm QEMU pipelines to test this. @achamayou has been fixing the very issues you have seen. :)

**Comment by SchrodingerZhu** [comment]
fixed by #147
