### ISSUE TITLE
Use ring-buffer with CAS-free, is it possible?

### ISSUE THREAD

**Issue by dingsp** [microsoft/snmalloc#152]
Hello, I write a demo @https://github.com/dingsp/fc_malloc2 use garbage-collector thread to collect the free block, and give it to ring-buffer, thread can consume block from ring-buffer with CAS-free, if the ring-buffer has no data, the thread will finally get block from os. The demo is based on fc_malloc which is not perfect.

**Comment by mjp41** [comment]
What is your aim?  Replacing a lock-free data structure that uses CAS, with a blocking data structure that does not use CAS is possible, but I you need to set out why you are intending to do this.

Ring-buffers are inherently blocking as they have a finite capacity, if a thread places too many free items into the ring-buffer, then it will have to wait for the consuming thread to process them.  That is why most allocators that use some form of cross thread messaging use an unbounded data-structure, typically using the freed object as the entry in that data-structure.  `snmalloc` uses an unbounded wait-free (non-lineariable) multi-producer single-consumer queue.  

Ring-buffers are good if 
* there is no suitable candidate for the nodes in the data-structure,
* if you are crossing a trust boundary and want a finite data-structure shared between the parties
* if you want the consumer to be able to apply back pressure to the producer
None of these criteria apply to an allocator.

**Comment by dingsp** [comment]
Thanks to replay.

The aim using  ring-buffers is to use atomic operation to control concurrency, since atomic operation seems fast than CAS. Ring-buffers can insure using atomic operation only when there are only one producer.

It is a problem that too many items in ring-buffers. So we do not produce many items into ring-buffers before thread consuming(may be failure).

To insure ring-buffer good:

- The producer at most produce ring-buffers size items. If last produced items did not be consumed, the producer will not produce next time.

- The most free blocks are cached in a double-linked list in the producer thread and can be merged. The ring-buffers are classified according to size-class, so finally there will be some large blocks to be produced.

-  If the thread fail to consume, it will finally use mmap to apply a memory and then cache it.

**Comment by mjp41** [comment]
I think this makes sense for an allocator designed like fcmalloc to fill the thread local caches from the GC thread.  I cannot see how this could be applied to `snmalloc`, so I am going to close this issue here.  Good luck with your prototyping.
