### ISSUE TITLE
PALOpenEnclave::reserve should the loop condition be inverted?

### ISSUE THREAD

**Issue by anakrish** [microsoft/snmalloc#155]
The `reserve` function is currently implemented thus: https://github.com/microsoft/snmalloc/blob/0a081cacd649e138cb83edb56f773c7ecf6b6e2d/src/pal/pal_open_enclave.h#L38-L49

The loop condition is currently:
`while (oe_base.compare_exchange_strong(old_base, next_base))`.

Should the condition instead be negated as:
`while ( ! oe_base.compare_exchange_strong(old_base, next_base))`
so that the loop immediately terminates after a successful update of `oe_base`?

**Comment by mjp41** [comment]
You are correct.  That worked in the unit tests as I haven't got anything covering racing on this code. I'll submit a PR to address this and #156.

**Comment by mjp41** [comment]
Closed by #157.
