### ISSUE TITLE
PALOpenEnclave: When out of memory NULL ought to be returned instead of calling oe_abort

### ISSUE THREAD

**Issue by anakrish** [microsoft/snmalloc#156]
The following test fails with `USE_SNMALLOC` and heap-pages bumped up to 4096.

https://github.com/openenclave/openenclave/blob/17f9ee3b4d7a84125b5fe083a92013de2c83c190/tests/stdc/enc/enc.cpp#L275-L276

**Comment by mjp41** [comment]
Closed by #157
