### ISSUE TITLE
Broken build on x86_64 GCC environment 

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#168]
broken in `gcc-9`, `mingw-w64 gcc 9` and `gcc-10`
see https://travis-ci.com/github/SchrodingerZhu/snmalloc-rs/jobs/318380181.
also reproduced locally on my archlinux.

**Comment by SchrodingerZhu** [comment]
> Starting with GCC 9, -Warray-bounds detects cases when memset is called
starting on a member of a struct but the size to be cleared ends up
writing over further members.

**Comment by mjp41** [comment]
This appears to have been caused by #166. I guess the call `function_ref` is confusing the static analysis. But it is quite strange as the `SNMALLOC_ASSUME` had previously fixed this.  I am going to disable this warning as it causes more trouble than it is worth.
