### ISSUE TITLE
Compile-time fixes for Clang 10

### ISSUE THREAD

**Issue by aganea** [microsoft/snmalloc#180]
Hello,
Would you mind applying these fixes to make the codebase compile with Clang 10 please?
Many thanks!
```
diff --git a/src/ds/aba.h b/src/ds/aba.h
index 21950ff..60dcc2f 100644
--- a/src/ds/aba.h
+++ b/src/ds/aba.h
@@ -121,6 +121,7 @@ namespace snmalloc
       }
 
       Cmp(const Cmp&) = delete;
+      Cmp(Cmp&&) = default;
     };
 
     // This method is used in Verona
diff --git a/src/ds/helpers.h b/src/ds/helpers.h
index b479011..8f5b83c 100644
--- a/src/ds/helpers.h
+++ b/src/ds/helpers.h
@@ -14,7 +14,7 @@ namespace snmalloc
   class Singleton
   {
     inline static std::atomic_flag flag;
-    inline static std::atomic<bool> initialised = false;
+    inline static std::atomic<bool> initialised{};
     inline static Object obj;
 
   public:
diff --git a/src/ds/mpscq.h b/src/ds/mpscq.h
index d5d5161..a397354 100644
--- a/src/ds/mpscq.h
+++ b/src/ds/mpscq.h
@@ -14,7 +14,7 @@ namespace snmalloc
       std::is_same<decltype(T::next), std::atomic<T*>>::value,
       "T->next must be a std::atomic<T*>");
 
-    std::atomic<T*> back = nullptr;
+    std::atomic<T*> back{};
     T* front = nullptr;
 
   public:
@@ -72,10 +72,10 @@ namespace snmalloc
         SNMALLOC_ASSERT(front);
         std::atomic_thread_fence(std::memory_order_acquire);
         invariant();
-        return std::pair(first, true);
+        return std::pair<T*, bool>(first, true);
       }
 
-      return std::pair(nullptr, false);
+      return std::pair<T*, bool>(nullptr, false);
     }
   };
 } // namespace snmalloc
diff --git a/src/mem/alloc.h b/src/mem/alloc.h
index c58015b..4f8aed8 100644
--- a/src/mem/alloc.h
+++ b/src/mem/alloc.h
@@ -240,6 +240,9 @@ namespace snmalloc
     template<size_t size>
     void dealloc(void* p)
     {
+      if (p == nullptr)
+        return;
+
 #ifdef USE_MALLOC
       UNUSED(size);
       return free(p);
@@ -280,6 +283,9 @@ namespace snmalloc
      */
     SNMALLOC_FAST_PATH void dealloc(void* p, size_t size)
     {
+      if (p == nullptr)
+        return;
+
 #ifdef USE_MALLOC
       UNUSED(size);
       return free(p);
@@ -302,6 +308,9 @@ namespace snmalloc
 
     SNMALLOC_SLOW_PATH void dealloc_sized_slow(void* p, size_t size)
     {
+      if (p == nullptr)
+        return;
+
       if (size == 0)
         return dealloc(p, 1);
 
@@ -325,6 +334,9 @@ namespace snmalloc
      */
     SNMALLOC_FAST_PATH void dealloc(void* p)
     {
+      if (p == nullptr)
+        return;
+
 #ifdef USE_MALLOC
       return free(p);
 #else
diff --git a/src/mem/pagemap.h b/src/mem/pagemap.h
index fc3da85..e658cd3 100644
--- a/src/mem/pagemap.h
+++ b/src/mem/pagemap.h
@@ -188,7 +188,7 @@ namespace snmalloc
       {
         PagemapEntry* value = get_node<create_addr>(e, result);
         if (unlikely(!result))
-          return std::pair(nullptr, 0);
+          return std::pair<Leaf*, size_t>(nullptr, 0);
 
         shift -= BITS_PER_INDEX_LEVEL;
         ix = (static_cast<size_t>(addr) >> shift) & ENTRIES_MASK;
@@ -208,11 +208,11 @@ namespace snmalloc
       Leaf* leaf = reinterpret_cast<Leaf*>(get_node<create_addr>(e, result));
 
       if (unlikely(!result))
-        return std::pair(nullptr, 0);
+        return std::pair<Leaf*, size_t>(nullptr, 0);
 
       shift -= BITS_FOR_LEAF;
       ix = (static_cast<size_t>(addr) >> shift) & LEAF_MASK;
-      return std::pair(leaf, ix);
+      return std::pair<Leaf*, size_t>(leaf, ix);
     }
 
     template<bool create_addr>
diff --git a/src/mem/pooled.h b/src/mem/pooled.h
index 71f8d91..f044a77 100644
--- a/src/mem/pooled.h
+++ b/src/mem/pooled.h
@@ -14,7 +14,7 @@ namespace snmalloc
     friend class MPMCStack;
 
     /// Used by the pool for chaining together entries when not in use.
-    std::atomic<T*> next = nullptr;
+    std::atomic<T*> next{};
     /// Used by the pool to keep the list of all entries ever created.
     T* list_next;
     std::atomic_flag in_use = ATOMIC_FLAG_INIT;
diff --git a/src/mem/remoteallocator.h b/src/mem/remoteallocator.h
index 4c1f906..6d8ae55 100644
--- a/src/mem/remoteallocator.h
+++ b/src/mem/remoteallocator.h
@@ -19,7 +19,7 @@ namespace snmalloc
     union
     {
       Remote* non_atomic_next;
-      std::atomic<Remote*> next = nullptr;
+      std::atomic<Remote*> next{};
     };
 
     alloc_id_t allocator_id;
diff --git a/src/mem/slowalloc.h b/src/mem/slowalloc.h
index f2fcba1..0ab1169 100644
--- a/src/mem/slowalloc.h
+++ b/src/mem/slowalloc.h
@@ -63,6 +63,6 @@ namespace snmalloc
    */
   inline SlowAllocator get_slow_allocator()
   {
-    return SlowAllocator{};
+    return {};
   }
 } // namespace snmalloc
diff --git a/src/pal/pal_consts.h b/src/pal/pal_consts.h
index 538f90d..fe9a38d 100644
--- a/src/pal/pal_consts.h
+++ b/src/pal/pal_consts.h
@@ -78,7 +78,7 @@ namespace snmalloc
     /**
      * List of callbacks to notify
      */
-    std::atomic<PalNotificationObject*> callbacks = nullptr;
+    std::atomic<PalNotificationObject*> callbacks{};
 
   public:
     /**
diff --git a/src/pal/pal_windows.h b/src/pal/pal_windows.h
index ba7fcea..8015827 100644
--- a/src/pal/pal_windows.h
+++ b/src/pal/pal_windows.h
@@ -17,7 +17,7 @@
 #  ifdef NTDDI_WIN10_RS5
 #    if (NTDDI_VERSION >= NTDDI_WIN10_RS5) && \
       (WINVER >= _WIN32_WINNT_WIN10) && !defined(USE_SYSTEMATIC_TESTING)
-#      define PLATFORM_HAS_VIRTUALALLOC2
+//#      define PLATFORM_HAS_VIRTUALALLOC2
 #    endif
 #  endif
```

**Comment by mjp41** [comment]
Thanks for these. I will look into these later.

I think the `free(nullptr)` test on Windows can be fixed in a different way.  I assume you were getting an AV on that where it tries to access the page map associated with 0, and fails.

**Comment by mjp41** [comment]
Is the
```C
+      if (p == nullptr)
+        return;
+
```
Just required to make the compiler happy. Freeing nullptr should work on windows, at least based on my testing. Could you clarify the need here. I would sooner add assumes in the right places for this.

**Comment by aganea** [comment]
It was causing a runtime crash. caused by a call to `::operator delete(void* p)` where the `p` was `nullptr`.

**Comment by mjp41** [comment]
Okay. Thanks. Will fix

**Comment by SchrodingerZhu** [comment]
before c++14,
> If expression evaluates to a null pointer value, no destructors are called, and the deallocation function may or may not be called (it's implementation-defined), but the default deallocation functions are guaranteed to do nothing when handed a null pointer. 

for delete expression, since c++14:

> If expression evaluates to a null pointer value, no destructors are called, and the deallocation function is not called. 


For delete functions:

> In all cases, if ptr is a null pointer, the standard library deallocation functions do nothing. If the pointer passed to the standard library deallocation function was not obtained from the corresponding standard library allocation function, the behavior is undefined.

> After the standard library deallocation function returns, all pointers referring to any part of the deallocated storage become invalid. 

for `std::free`,

> If ptr is a null pointer, the function does nothing. 

An interesting thing is cppreference seems to have a conflict with `iso N4835` on delete expressions, where ISO standards claims:
> If the value of the operand of the delete-expression is a null pointer value; it is unspecified whether a deallocation function will be called as described above.

Anyway, delete expression should not be our concern; but I think it is better to let deallocation functions do nothing here to keep consistent with the behavior of standard library.

**Comment by mjp41** [comment]
@aganea was it a call to 
```
::operator delete(void* p, size_t size)
```
The code path where there is a size assumes it is actually an allocation, but I think calling `delete` on a `T*`  where is it `nullptr` would result in a sized deallocation of `nullptr` with `sizeof(T)`.

**Comment by mjp41** [comment]
So I didn't need those changes to compile with 
* Windows with clang-cl 
* Windows with Clang 10.0.0 with GNU-like command-line
* Linux with Clang 10

Could you clarify your build options that require these changes.  Or if there is a branch or something I can use to repro.  I would like to ensure this works for you going forward by adding something to CI, and I can't currently repro the requirement for the changes.

**Comment by aganea** [comment]
I'm compiling snmalloc as part of LLVM, using clang-cl 10.0, on a "x64 Native Tools Command Prompt for VS 2019" (I think that part is important), with the latest VS2019 16.5.4 and latest Windows Kit 10.0.18362.
A full repro can be found here: https://github.com/mjansson/rpmalloc/issues/150
However after applying D71786, you would need to replace the rpmalloc files by the snmalloc ones, in `llvm/lib/Support/CMakeLists.txt`:
```
  set(RPMALLOC_FILES "D:/git/snmalloc/src/override/malloc.cc" "D:/git/snmalloc/src/override/new.cc")
```
Then follow the instructions in the link above. Please let me know how that goes.

**Comment by mjp41** [comment]
If it is possible to extract the command line for building malloc.cc compilation unit that has the errors that would be super useful.  Otherwise, I will set up a machine to build llvm on Windows tomorrow.

**Comment by aganea** [comment]
Here it is:
```
clang-cl.exe  /nologo -TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib\\Support -ID:\\llvm-project\\llvm\\lib\\Support -Iinclude -ID:\\llvm-project\\llvm\\include /GS- /D_ITERATOR_DEBUG_LEVEL=0 -Xclang -O3 -fstrict-aliasing -march=skylake-avx512 -flto=thin -fwhole-program-vtables -fuse-ld=lld /Zc:inline /Zi /Zc:strictStrings /Oi /Zc:rvalueCast /W4  -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wstring-conversion /Gw -flto=thin /MT /O2 /Ob2 /DNDEBUG   -std:c++14 /showIncludes /Folib\\Support\\CMakeFiles\\LLVMSupport.dir\\D_\\git\\snmalloc\\src\\override\\malloc.cc.obj /Fdlib\\Support\\CMakeFiles\\LLVMSupport.dir\\LLVMSupport.pdb -c D:\\git\\snmalloc\\src\\override\\malloc.cc"
```

**Comment by mjp41** [comment]
I think the majority of the patch you have is due to it being compiled with C++14 rather than C++17.

**Comment by aganea** [comment]
Yes, probably, I can try with C++17, however that is part of the LLVM community policies. That won't change that on the short term. Do you object supporting clients compiling with C++14?

**Comment by mjp41** [comment]
#182 should make it compile with C++14, but it will have warnings as we use C++17 features. E.g.

```
c:\\src\\snmalloc\\src\\override/../mem/mediumslab.h(91,10): warning: constexpr if is a C++17 extension
      [-Wc++17-extensions]
      if constexpr (zero_mem == YesZero)
```

**Comment by davidchisnall** [comment]
We make quite heavy use of C++17 features because doing so helps with code quality.  Given that we can compile with gcc, clang, and Visual Studio, I don't see a benefit in moving everything to an earlier version of the standard and I do see a cost.

As I recall, LLVM has an option in CMake to build in C++17 mode.  I'd suggest that, for LLVM use, snmalloc be guarded by this flag: don't build it unless you are in C++17 mode.  That would allow people on older platforms to build with the default allocator and people using a compiler from the last 3 or so years to gain the benefit.

**Comment by aganea** [comment]
Sounds good with me. I'll add a warning to the snmalloc integration into LLVM. Last time I compiled LLVM with C++17 there were a few issues, but I'd rather fix & push them upstream, I hope at some point they will move past C++14 (but that all depends on baseline compiler in the distros they want to support).
Many thanks again for the help!
