### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#192]
Before #178
```
redis sn_79ca9 8.984 56332 3.58 0.85 0 303
```
after 
```
redis sn_c899e 11.345 56172 4.78 0.87 0 304
```

This perf regressions needs fixing.

**Comment by mjp41** [comment]
I think the issue is rounding up the zeroing of a large callocs.  Prior to this commit, we only zeroed the requested memory, but due to an issue with not committing enough memory on Windows for large reallocs, we now commit the whole range.

**Comment by mjp41** [comment]
Unfortunately, it appears the performance regression occurs here:
```
-  if (sz == sizeclass_to_size(size_to_sizeclass(size)))
+ if (sz == round_size(size))
```
But this is actually fixing a bug.  So our perf for redis, was not correct.  I can investigate why we are slower than mimalloc.  But sadly it is not going to be an easy fix.

**Comment by mjp41** [comment]
@schrodingzhu do you know how to get perf traces from redis?

**Comment by Theodus** [comment]
Looking at `round_size`, we should be able to avoid the branch in `bits::next_pow2`, since `size_to_sizeclass(NUM_SIZECLASSES - 1)` is probably greater than 2.

**Comment by Theodus** [comment]
Never mind, it seems that the compiler figures that out

**Comment by SchrodingerZhu** [comment]
you mean `perf record`?

**Comment by mjp41** [comment]
@SchrodingerZhu  yep.

**Comment by SchrodingerZhu** [comment]
[perf.zip](https://github.com/microsoft/snmalloc/files/4660893/perf.zip)

**Comment by SchrodingerZhu** [comment]
emmm, `-O3` may remove lot of information here. Should I downgrade the opt-level?

**Comment by SchrodingerZhu** [comment]
Onedrive: 
https://schrodinger-my.sharepoint.com/:u:/g/personal/i_zhuyi_fan/EdhyRKSNBRdHvGjbyCqtR7IB7yznKjNs_63S8Vm2650dqw?e=AZ6OFZ

mirror cowtransfer:
https://c-t.work/s/cc5fc7bc14bc47

**Comment by mjp41** [comment]
My version of `perf` can't open your files. 
```
file uses a more recent and unsupported ABI (8 bytes extra)
```
Would you be able to just send the top-level functions numbers
```
perf report > basic.txt
```
I think it might be hitting the large alloc path, and that has fairly bad codegen, so might be slow.  But want to see how much time is spent there before trying to improve.

**Comment by SchrodingerZhu** [comment]
[basic-snmalloc.txt](https://github.com/microsoft/snmalloc/files/4661447/basic-snmalloc.txt)
[basic-mimalloc.txt](https://github.com/microsoft/snmalloc/files/4661449/basic-mimalloc.txt)

**Comment by mjp41** [comment]
Based on the traces it looks like the majority of time is spent in realloc in the mimalloc trace.  The snmalloc one looks a bit weird as I don't even see realloc?  Did you use the same settings for both.

`mimalloc` has a custom `realloc` path, where as `snmalloc` just uses the `alloc_size`, `alloc` and `dealloc` routines at the top level. Perhaps, adding a custom routine would improve performance.

**Comment by mjp41** [comment]
#209 fixes the performance regression.  I had incorrectly implemented `rounded_size` great job, @theodus.

**Comment by mjp41** [comment]
The perf is now:
```
redis sn 8.991 56224 3.65 0.81 0 304
```

**Comment by mjp41** [comment]
@schrodingerzhu, please reopen this issue if you don't see performance heading back to the original perf.
