### ISSUE TITLE
OpenEnclave: Compilation fails with -nostdinc due to cpuid.h inclusion

### ISSUE THREAD

**Issue by anakrish** [microsoft/snmalloc#200]
`cpuid.h` is not available within the enclave and compiling with `-nostdinc` results in the following:

Building CXX object 3rdparty/snmalloc/CMakeFiles/oesnmalloc.dir/allocator.cpp.o
cd /home/anakrish/work/repo2/build/3rdparty/snmalloc && export CCACHE_CPP2=true && /usr/bin/ccache /usr/bin/clang++-7   -I/home/anakrish/work/repo2/build/output/include/openenclave/libcxx -I/home/anakrish/work/repo2/build/output/include/openenclave/libc  -g -O0   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -I/home/anakrish/work/repo2/include -I/home/anakrish/work/repo2/3rdparty/libcxx/libcxx/include -I/home/anakrish/work/repo2/3rdparty/musl/musl/include -I/home/anakrish/work/repo2/build/output/include/openenclave/libc -Wno-conversion -Wno-macro-redefined -ftls-model=local-exec -nostdinc -nostdinc++ -fPIE -ffreestanding -mcx16 -fno-exceptions -fvisibility=hidden -std=c++14 -std=c++17 -o CMakeFiles/oesnmalloc.dir/allocator.cpp.o -c /home/anakrish/work/repo2/3rdparty/snmalloc/allocator.cpp
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/allocator.cpp:30:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/malloc.cc:1:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/slowalloc.h:1:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/globalalloc.h:3:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/../ds/helpers.h:3:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/../ds/bits.h:8:
In file included from /home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/../ds/../aal/aal.h:131:
/home/anakrish/work/repo2/3rdparty/snmalloc/./snmalloc/src/override/../mem/../ds/../aal/aal_x86.h:7:12: fatal error: 'cpuid.h' file not found
#

**Comment by mjp41** [comment]
So PLATFORM_IS_X86_SGX is not being defined, as your build is using the standard x86 abstraction layer. @achamayou can you look at this.

**Comment by achamayou** [comment]
Solved in https://github.com/anakrish/openenclave/pull/1
