### ISSUE TITLE
Consider supporting snmalloc in Ubuntu 16.04 (GCC 5.4.0)

### ISSUE THREAD

**Issue by anakrish** [microsoft/snmalloc#208]
snmalloc does not compile with the default GCC (5.4.0) on Ubuntu 16.04. This is due to the use of specific C++17 features like `if constexpr`. 
As part of PR https://github.com/openenclave/openenclave/commit/efd9311ff3cb84f6b0e44c581867fa618cf9060c, I had to disable snmalloc build on Ubuntu 16.04 when the compiler is GCC.

Consider supporting default compilers of slightly older platforms like Ubuntu 16.04. That would make adopting snmalloc easier.

**Comment by mjp41** [comment]
Supporting  a four year old compiler is not something we are resourced to do.  As 18.04 LTS is out surely Open Enclave should be pushing for people to use that.  Also all the security features around spectre mitigations, etc. are completely missing from GCC 5.4.0.   There are clang packages for 16.04, so the snmalloc component could be built with clang, and linked in.

The core difficulty is not the `if constexpr` but the `inline static` fields.  Prior to C++17 on GCC this required hideous template hacks to get the desired behaviour.

Is this actually a customer requirement for OE?  We are happy to support an engineer in back-porting C++14, if someone else funds it.

**Comment by SchrodingerZhu** [comment]
@anakrish for older ubuntu release, there is a repo to get up-to-date toolchains: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

**Comment by mjp41** [comment]
16.04 is no longer required for OE.  Closing this.
