### ISSUE TITLE
AddressSpaceManager::reserve sometimes always asks for the smallest possible block?

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#230]
In the case that `AddressSpaceManager::reserve` cannot satisfy a request from its cache and the underlying PAL supports highly-aligned allocations, the requested block size is taken to be the smallest permitted by the PAL:

https://github.com/microsoft/snmalloc/blob/4e1f5829a754ab9c170ec090979d3a670d2d5d1a/src/mem/address_space.h#L197-L201

This allocation is then inserted into the AddressSpaceManager's cache

https://github.com/microsoft/snmalloc/blob/4e1f5829a754ab9c170ec090979d3a670d2d5d1a/src/mem/address_space.h#L229

and then an attempt is made to return a chunk of the originally requested size, with commentary suggesting that it cannot fail

https://github.com/microsoft/snmalloc/blob/4e1f5829a754ab9c170ec090979d3a670d2d5d1a/src/mem/address_space.h#L231-L232

This seems... fishy, since the `PAL`s that support `AlignedAllocation` have `minimum_alloc_size` of 4KiB or 64KiB, well below the typical 1MiB (or 16MiB) of a `Superslab`.

**Comment by mjp41** [comment]
Doesn't the line: 
https://github.com/microsoft/snmalloc/blob/4e1f5829a754ab9c170ec090979d3a670d2d5d1a/src/mem/address_space.h#L181-L186

Ask for the blocks above minimum size?  Does this address your issue?

**Comment by nwf** [comment]
Yes, thanks.
