### ISSUE TITLE
Revisiting CHERI rederivation w/ 1MiB Superslabs.

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#231]
After #229 landed, the default granularity of the chunkmap is 1 MiB, meaning that a 48 bit address space requires a 256 MiB flat pagemap.  That's large, but not unreasonably huge.  Unfortunately, the approach suggested in #198 stores a full CHERI capability for every granule, which is to say that this is suddenly 4 GiB, which is... probably an unreasonable thing to ask.  The CHERI `lld` and CheriBSD kernel both look askance at objects declaring their `.bss` to be so substantial.

I wonder if it's reasonable, then, to suggest some kind of hybridized design, wherein the pagemap stores something like...

```
struct {
  void * __capability amplifier;
  enum ChunkMapSuperslabKind superkinds[16]; /* uint8_t[16], really */
}
```

This would require only 512 MiB in the flat pagemap, but requires that we be asking the kernel for 16 MiB (sized and aligned) regions of AS even if we are internally parcelling them out in 1 MiB increments, requiring that the `AddressSpaceManager` allocator be brought in to the CHERI story.  Further, the interface to the chunkmap would need to be adjusted to understand that it operates on two different granularities, one for amplification and one for `ChunkMapSuperslabKind` values.

Assuming this multiple-granularity idea passes the smell test, three follow-on design decisions present themselves:

* Rather than packing the two kinds of state into one table, should we instead use two pagemaps, one for amplifiers and one for superkinds?  Note that `dealloc(p)` will need both pieces of state (though `dealloc(p,n)` and `dealloc<n>(p)` may just need the amplifiers, unless we're `CHECK_CLIENT`-ing).

* The exact choice of "16" is not required, but seemed to get the metadata size down while not grossly inflating the required alignment of amplification granules and preserving cacheline-adjacency of amplifiers and superkinds.

* #198 was using the freedom of the `offset` field within the CHERI capability to encode the `ChunkMapSuperslabKind`, because our amplifiers are always highly-aligned.  In this design, these bits are now available for reuse, so: is there anything else we'd like to store there?

**Comment by mjp41** [comment]
That seems reasonable to me.

In the highly address space constrained world we are already not using the flat map, so reserving larger space for this scenarios seems reasonable.

The Pal could perhaps contain the amplification code, then it grabs blocks that are larger.  I.e. you could make the 4GiB that is returned by `reserve_at_least` be the unit of amplification?

**Comment by davidchisnall** [comment]
I think this sounds quite reasonable.  As long as the rederivation chain doesn't present a privilege elevation mechanism.  For the cross-domain case, the size and alignment of a sandbox must be a multiple of the larger chain.  We lose some hardware mitigation against accidental errors in the allocator code, but that's not really worth worrying about.  64 or 128 MiB should be fine as a granule size for sandboxes.

**Comment by nwf** [comment]
Potentially, we could have misaligned sandboxes, too, so long as we know we'll never need to expand their heaps within the amplification granule.  That is, if an amplifier capability only covers some of the 1 MiB chunks within its granule (and the others are `NotOurs` in the chunkmap), then I think everything works out fine.

**Comment by nwf** [comment]
This no longer reflects our current thinking on CHERI amplification; at present, we have chosen instead to amplify on much grander scales, GiB or larger, giving us a small Pagemap-backed AuthMap.  The co-mingling approach may remain viable and may be more interesting for constrained use cases as part of a larger system (e.g., a sandbox-private `snmalloc` on a platform with 64 bit addresses but much smaller effective AS for the sandbox).  If the approach being explored for #267 goes well, moving to another design will just require supplying an alternate `AddressSpaceManager` and cooperative `ChunkMap`.
