### ISSUE TITLE
Provide API for memory usage from snmalloc

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#240]
@achamayou has raised an [issue (3410)](https://github.com/openenclave/openenclave/pull/3410
) for exposing malloc information inside open-enclave.  The basic structure to return is:

```C
struct oe_mallinfo_t {
  size_t max_total_heap_size;
  size_t current_allocated_heap_size;
  size_t peak_allocated_heap_size;
}
```

I propose adding this to snmalloc.  I propose interpreting the fields as the following

* `max_total_heap_size` -  the amount of address space reserved so far for the heap.  
* `peak_allocated_heap_size` - the amount of address space the `AddressSpaceManager` has passed to the allocator for use as meta-data or object-data.
* `current_allocated_heap_size` - the amount of memory that is in the large allocator unused subtracted from `peak_allocated_heap_size`.

These statistics would only be tracked at the chunk level granularity, so 1MiB by default. This means we can get consistent numbers without introducing per-thread synchronisation.  The `AddressSpaceManager` can accurately track sub-chunk meta data amount accurately.  These statistics can be live updated at minimal cost as they are not on any fast paths.

For some Pal's `max_total_heap_size` will not be much use. In particular, on Windows and FreeBSD where the `AddressSpaceManager` does not have to do much work, as the platform provides aligned allocations, then `max_total_heap_size` will be very close to `peak_allocated_heap_size`, only unused meta-data space will affect this.

CC: @sylvanc @davidchisnall 

@licenser @darach, Do you have any requirement for memory usage statistics from `snmalloc`?

**Comment by davidchisnall** [comment]
Can we track some analogue of the commit charge (i.e. subtract the memory that we've marked as not used)?  In most PALs (though not the OE one), this has some serialisation effect because it's a syscall that touches the VM subsystem - maybe only collect this on PALs where we're doing a syscall?

**Comment by mjp41** [comment]
With this, `current_allocated_heap_size` would be a pretty accurate reflection of commit charge with prompt decommit.  With lazy decommit, it is the commit charge that would remain after a low-memory notification.

With lazy-commit/overcommit, we are not tracking the RSS associated with the allocator.

**Comment by mjp41** [comment]
@achamayou I am not sure that `max_total_heap_size` is something I want to provide from `snmalloc` it seems more like the platform should specify it. I guess for your use case in OE. It would be fine for you to fill in that value, and snmalloc would provide you the other two values.

**Comment by achamayou** [comment]
@mjp41 agreed, what could be nice is to get a sense of how much space snmalloc need for metadata, so we can expose `total enclave heap - metadata size` there, but it's also fine if that's not possible.

**Comment by mjp41** [comment]
I don't think the meta-data is particularly high percentage.  Meta-data is include in the peak and current statistics in #241.  I don't track object and meta data usage separately. I could if it is really important, but the overall consumption is what you need to provision.

**Comment by achamayou** [comment]
Ok, that’s fine, the total heap size is a pure OE-side calculation then.

**Comment by davidchisnall** [comment]
If we’re exposing this structure in release builds, it becomes part of our public ABI and so we should add a version or size field so that consumers can check that all of the fields that they expect are there.

**Comment by mjp41** [comment]
Good point @Davidchisnall. I am not sure what the right way to expose the data is.  In #241, the C++ API exposes a function returning a std::pair of current and peak, but this is probably not what you want in a C API. I don't really want to directly expose a global. I could provide a funcion that takes a ptr to a struct, and fills it in with suitable data, with constraints on version and size.  Or it could just have two functions one for current and one for peak.  You can't then read them atomically, but that probably doesn't mater anyway as the stats are an approximation anyway.

**Comment by achamayou** [comment]
I think for now it would be fine to add this as an extension (and make it clear in comment/file name that it is), and to not include it in builds that can be LD_PRELOADed. Only users who build and link directly would be able to optionally build it in, and will need to rebuild if a code update changes the stats struct (but then they would rebuild anyway when they upgrade snmalloc).

If ABI compat was a goal (but I don't think it's necessary), then oe_mallinfo_t could be opaque, and snmalloc could expose an oe_mallinfo_alloc/oe_mallinfo_free pair and some accessors (oe_mallinfo_get_current_allocated_heap_size etc).
