### ISSUE TITLE
install target

### ISSUE THREAD

**Issue by armintoepfer** [microsoft/snmalloc#250]
Please consider adding an `install` target to cmake.

Cheers, Armin

**Comment by mjp41** [comment]
@achamayou, @davidchisnall do you have thoughts on the correct way to do this with respect to versioning?

I propose we install 
```
libsnmallocshim.so
libsnmallocshim-1mib.so
libsnmallocshim-16mib.so
libsnmallocshim-static.a
libsnmallocshim-static-1mib.a
libsnmallocshim-static-16mib.a
```

I don't think we need to install the Rust static library, as that is only consumed via the crate.  If we expose, functions beyond the standard malloc interface, then we could expose a header, but currently we only do that via the header only version of the library, i.e. how Verona consumes it.

I don't think there is anything to install for the Open Enclave target as that is consumed and published via Open enclave.

Any thing else I should consider for this?

**Comment by achamayou** [comment]
There is no need of an install target for Open Enclave. I suppose the .so could be versioned as .so.0 just in case?

**Comment by mjp41** [comment]
We now have an install target.
