### ISSUE TITLE
Typo in macro definition in CMakeLists.txt

### ISSUE THREAD

**Issue by rmn30** [microsoft/snmalloc#253]
At https://github.com/microsoft/snmalloc/blob/49b9856ed0f4681e41e16576aff968c817f19368/CMakeLists.txt#L262 the macro definition is missing and 'L' in SNMALLOC. This means the 16MiB shared library shim has been using the default 1MiB chunk size since 4e1f5829a754ab9c170ec090979d3a670d2d5d1a .

**Comment by mjp41** [comment]
Closed by #254
