### ISSUE TITLE
option to disable tests

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#261]
in some cases one may want to add `snmalloc` as a subdirectory cmake project; however, they may not want to include library tests in the super project.

**Comment by mjp41** [comment]
Is `SNMALLOC_ONLY_HEADER_LIBRARY` not sufficient for your needs? Do you want it to build the library targets?  That is what we use in Verona:
https://github.com/microsoft/verona/blob/4b1022ac77f3cc3ab05e97af62409d32cd36ffed/src/rt/CMakeLists.txt#L4-L5

**Comment by SchrodingerZhu** [comment]
oh, my fault. I think it is perfect already.
