### ISSUE TITLE
Extension of snmalloc for Pyoxidizer (python embedded in rust)

### ISSUE THREAD

**Issue by ryancinsight** [microsoft/snmalloc#289]
Hello again @mjp41, I started looking over the source code and found it should be simple enough to extend the options to rust and python for our use case and it looks like I should be able to obtain everything from src/override/malloc.cc. However, can you explain the "SNMALLOC_NAME_MANGLE(realloc)", i.e. what is the extern name that I am calling from rust here? I did some simple tests moving code from malloc.cc to rust.cc and naming directly sn_realloc, sn_free, sn_malloc for use in rust, which works fine, but I'm sure you would rather not have duplicates in the code but I am unfamiliar with Name_mangle definitions.

Best

**Comment by mjp41** [comment]
So this lets you define the name you want to call.  

For instance,
https://github.com/microsoft/snmalloc/blob/a1fc509a65cc68a8746ce21681e51dcb1fde531a/src/test/func/malloc/malloc.cc#L4-L5

Is building snmalloc, but with all the standard C things prefixed with `our_`.   E.g 

https://github.com/microsoft/snmalloc/blob/a1fc509a65cc68a8746ce21681e51dcb1fde531a/src/test/func/malloc/malloc.cc#L92

https://github.com/microsoft/snmalloc/blob/a1fc509a65cc68a8746ce21681e51dcb1fde531a/src/test/func/malloc/malloc.cc#L99

https://github.com/microsoft/snmalloc/blob/a1fc509a65cc68a8746ce21681e51dcb1fde531a/src/test/func/malloc/malloc.cc#L96

Probably, you want to do something like 

```C++
#define SNMALLOC_NAME_MANGLE(a) sn_##a
```

Then you will have all the `snmalloc` functions, but prefixed with `sn_`, so they don't conflict with the ones in libc.

Probably, the easiest thing to do is add
```C++
#define SNMALLOC_NAME_MANGLE(a) sn_##a
#include "malloc.cc"
```
inside `rust.cc`, and then expose the symbols inside `snmalloc-sys`:

https://github.com/SchrodingerZhu/snmalloc-rs/blob/master/snmalloc-sys/src/lib.rs

**Comment by ryancinsight** [comment]
This worked perfectly, only issue was slowalloc.h was being called more than once so I had to remove direct call. I tested rust crate symbols locally and will send to @SchrodingerZhu  crate with added tests once this is reviewed.

**Comment by mjp41** [comment]
Great.  I am not sure why that is included in the first place, and it should have a `pragma` to deal with the multiple includes. #291 addresses the second issue.
