### ISSUE TITLE
Need macOS 11 CI jobs

### ISSUE THREAD

**Issue by amari** [microsoft/snmalloc#337]
All of the CI checks passed in #336, but the build failed on macOS 11. The current CI jobs use macOS 10.15 . 

I ask that both macOS 10.15 and 11 be supported by the CI system. Apple has broken many existing and long-standing API conventions in their latest major and minor macOS 11 releases.

> @devnexen "It works on my machine™️". 

The most feared sentence for QA ever :-)
Build fails because of `abort` otherwise.

_Originally posted by @devnexen in https://github.com/microsoft/snmalloc/issues/336#issuecomment-861151024_

**Comment by mjp41** [comment]
So the current CI is Azure Pipelines.  This does not currently support macOS Big Sur 11:

  https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

This is however supported by Github actions.  

  https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I have been planning to move to Github actions, I think this would be a prerequisite to support.

Overall, it should be fairly straightforward to migrate most of the pipelines, but I am a little worried about the QEMU ARM tests and Docker, which might be some work.

I have a bit of a backlog of other work at the moment, so won't be able to start on this for a while.

**Comment by mjp41** [comment]
Just confirmed that this Project has access to the macOS 11 runs: #338.

**Comment by davidchisnall** [comment]
This is now fixed by the move to GitHub Actions for CI.
