### ISSUE TITLE
Library and binaries are >256MiB on Macos ARM64

### ISSUE THREAD

**Issue by hkratz** [microsoft/snmalloc#339]
Environment:
* Macbook Air M1, macOS Big Sur, everything updated

Reproduce:
* Clone latest git
* Build according to [build instructions for release mode](https://github.com/microsoft/snmalloc/blob/master/docs/BUILDING.md)

```
ls -lrS
[...]
-rw-r--r--    1 hans  staff   17441280 Jun 20 08:59 libsnmallocshim-16mib-static.a
-rw-r--r--    1 hans  staff  269043800 Jun 20 08:59 libsnmallocshim-static.a
-rw-r--r--    1 hans  staff  269043800 Jun 20 08:59 libsnmallocshim-1mib-static.a
-rwxr-xr-x    1 hans  staff  270654121 Jun 20 08:59 func-thread_alloc_external-1
-rwxr-xr-x    1 hans  staff  270655709 Jun 20 08:59 func-thread_alloc_external-check
-rwxr-xr-x    1 hans  staff  270660126 Jun 20 08:59 perf-contention-1
-rwxr-xr-x    1 hans  staff  270661294 Jun 20 08:59 perf-low_memory-1
-rwxr-xr-x    1 hans  staff  270662456 Jun 20 08:58 func-two_alloc_types-malloc
-rwxr-xr-x    1 hans  staff  270662626 Jun 20 08:59 perf-contention-check
-rwxr-xr-x    1 hans  staff  270662978 Jun 20 08:59 perf-low_memory-check
-rwxr-xr-x    1 hans  staff  270680900 Jun 20 08:59 perf-external_pointer-1
-rwxr-xr-x    1 hans  staff  270698498 Jun 20 08:59 libsnmallocshim.dylib
-rwxr-xr-x    1 hans  staff  270698503 Jun 20 08:59 libsnmallocshim-1mib.dylib
-rwxr-xr-x    1 hans  staff  270699824 Jun 20 08:59 perf-singlethread-1
-rwxr-xr-x    1 hans  staff  270700382 Jun 20 08:59 func-statistics-1
-rwxr-xr-x    1 hans  staff  270702377 Jun 20 08:59 libsnmallocshim-checks.dylib
-rwxr-xr-x    1 hans  staff  270704132 Jun 20 08:59 func-external_pagemap-1
-rwxr-xr-x    1 hans  staff  270704992 Jun 20 08:59 func-memory_usage-1
-rwxr-xr-x    1 hans  staff  270705688 Jun 20 08:59 perf-external_pointer-check
-rwxr-xr-x    1 hans  staff  270705848 Jun 20 08:59 func-external_pagemap-check
-rwxr-xr-x    1 hans  staff  270706756 Jun 20 08:59 func-memory_usage-check
-rwxr-xr-x    1 hans  staff  270708226 Jun 20 08:59 func-statistics-check
-rwxr-xr-x    1 hans  staff  270711130 Jun 20 08:59 func-malloc-1
-rwxr-xr-x    1 hans  staff  270711316 Jun 20 08:59 perf-singlethread-check
-rwxr-xr-x    1 hans  staff  270721091 Jun 20 08:59 func-first_operation-1
-rwxr-xr-x    1 hans  staff  270726599 Jun 20 08:59 func-first_operation-check
-rwxr-xr-x    1 hans  staff  270735438 Jun 20 08:59 func-malloc-check
-rwxr-xr-x    1 hans  staff  270740667 Jun 20 08:59 func-sandbox-1
-rwxr-xr-x    1 hans  staff  270745615 Jun 20 08:59 func-sandbox-check
-rwxr-xr-x    1 hans  staff  270749946 Jun 20 08:59 func-memory-1
-rwxr-xr-x    1 hans  staff  270769438 Jun 20 08:59 func-memory-check
-rwxr-xr-x    1 hans  staff  270815892 Jun 20 08:58 func-two_alloc_types-oe
-rwxr-xr-x    1 hans  staff  270864707 Jun 20 08:59 func-two_alloc_types-1
-rwxr-xr-x    1 hans  staff  270864724 Jun 20 08:58 func-two_alloc_types-16
-rwxr-xr-x    1 hans  staff  270868263 Jun 20 08:58 func-two_alloc_types-check
```

**Comment by hkratz** [comment]
It apparently include 256MiB of zeroes in the data section like this:
```
$ nm -n ./CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o|grep " D"
0000000000006000 D __ZN13snmalloc_host21GlobalPagemapTemplateINS_11FlatPagemapILm20EhEENS_11ForChunkmapEE14global_pagemapE

$ otool -l ./CMakeFiles/func-two_alloc_types-malloc.dir/src/test/func/two_alloc_types/alloc2.cc.o
[...]
Section
  sectname __data
   segname __DATA
      addr 0x0000000000006000
      size 0x0000000010000000
    offset 25944
     align 2^12 (4096)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
[...]
```

**Comment by nwf** [comment]
How unusual.  That's almost surely the `ChunkMap` (a byte per megabyte of the AS; 256MiB = 2^{28} as expected for a 48-bit address space; see https://github.com/microsoft/snmalloc/blob/master/src/mem/pagemap.h and https://github.com/microsoft/snmalloc/blob/master/src/mem/chunkmap.h for details if you're curious) and it really ought to be landing in `.bss` given that it's all zeros.

Do things get better if you chant `-DSNMALLOC_USE_CXX20` at `cmake` when building?  I ask because when `snmalloc` builds under C++17, the entries in PageMaps are `std::atomic<T>` types, but in C++20 they're just `T` and `std::atomic_view`s are used to access them (after https://github.com/microsoft/snmalloc/commit/80c6e952106677861a1c9bdbd7a47ae8e3d46ffb).  I wonder if your system's `std::atomic<T>`s are more like C++20s even when building in C++17 mode.  Out of curiosity, does compilation take many hundreds of megabytes or even gigabytes per target?

**Comment by mjp41** [comment]
@nwf I agree with your assessment that it is the chunkmap:
```
...
-rw-r--r--    1 hans  staff   17441280 Jun 20 08:59 libsnmallocshim-16mib-static.a
...
-rw-r--r--    1 hans  staff  269043800 Jun 20 08:59 libsnmallocshim-1mib-static.a
...
```
Makes that pretty evident to me, as the only difference between these two files would be the granularity of the chunkmap. With the 16MiB setting have a 16MiB chunkmap, and the 1mib setting having a 256MiB chunk map. 

But this should be in BSS, so shouldn't take up any space.  I wonder if the compiler is being cautious about the more relaxed ARM memory model for atomics?  

@hkratz which compiler and version are you using to compile with?

**Comment by hkratz** [comment]
> Do things get better if you chant `-DSNMALLOC_USE_CXX20` at `cmake` when building?

They do not get better if I use `cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DSNMALLOC_USE_CXX20=1`

I can reproduce it with snmalloc 0.5.0 too.

> @hkratz which compiler and version are you using to compile with?

```$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin```

I might be able to look into it more tomorrow.

**Comment by mjp41** [comment]
@devnexen do you also have the large binary size on your M1?

**Comment by hkratz** [comment]
It seems that `static inline` is lowered in a weird way on Mac OS X, on both ARM64 and x86_64. Even this simple test produces huge binaries:

container.h
```c++
#pragma once
#include <cstdint>

class Container {
    public:
        inline static uint8_t inner[256000000];
};
```

main.cc
```c++
#include "container.h"

int main() {
    return Container::inner[0];
}
```

ARM64/x86_64 does not matter:
```
$ clang -O3 -std=c++17 main.cc -o main; ls -l main
-rwxr-xr-x  1 hans  staff  258033441 Jun 21 12:58 main
~/dev/spikes/atomictest
$ clang -O3 -std=c++17 main.cc --target=x86_64-apple-darwin -o main; ls -l main
-rwxr-xr-x  1 hans  staff  256033040 Jun 21 12:58 main
```

**Comment by devnexen** [comment]
> @devnexen do you also have the large binary size on your M1?

same here but it seems to be an apple problem not just the arm64 flavor here on my old (real) Intel machine
`
ls -lh *.a
-rw-r--r--  1 dcarlier  staff    17M 14 Jun 15:14 libsnmallocshim-16mib-static.a
-rw-r--r--  1 dcarlier  staff   257M 14 Jun 15:13 libsnmallocshim-1mib-static.a
-rw-r--r--  1 dcarlier  staff   257M 14 Jun 15:14 libsnmallocshim-static.a
`

**Comment by hkratz** [comment]
See also https://stackoverflow.com/questions/68073293/why-do-static-inline-data-members-not-end-up-in-a-bss-section-on-macos

**Comment by mjp41** [comment]
@hkratz and @akaame thanks both for the investigation, and super interesting.  This is not something I can fix for the current master as it would break the header only way the library works.  However, we have been performing some major refactorings in the branch `snmalloc2`, this should not suffer these issues.  Though, I have not tested that. 

That branch has at least one known perf regressions, but will hopefully become master in the not too distant future.  It should be correct and functional, if your interested in testing for your use case.

**Comment by davidchisnall** [comment]
@hkratz and @Akaame, awesome work on the root-cause analysis, thanks!  I've pushed something in #364 that should force the global pagemap to the BSS section and a check that the binary size is moderately sane (no more than about ten times what it should be, so we shouldn't get false positives from the check).  

It looks as if this produces a 600 KiB test binary on macOS, which is a lot better than the 270 MiB you were seeing.
