### ISSUE TITLE
ds/bits contains decidedly not bit-like things

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#42]
`pause()`, `tick()`, `tickp()`, `halt_out_of_order()`, `benchmark_time_start()`, and `benchmark_time_end()` really seem like they belong somewhere else, probably within the PAL.  Is there a reason they're here instead?

**Comment by mjp41** [comment]
So I viewed `bits.h` as the CPU abstraction, and the `pal.h` as the OS/platform abstraction.  These are somewhat orthogonal, and if we put all the CPU abstraction stuff into each pal, then I think we will get a blow up in cases.  That said, it might be worth refactoring `bits.h`, to separate the CPU abstraction, from various bit manipulating code.

@sylvanc @davidchisnall thoughts?

**Comment by sylvanc** [comment]
It's a good point. I think a timing.h containing all the functions @nwf mentions would be good. Possibly also separating out SNMALLOC_ASSUME and Construction. I think the PAL isn't quite right, as the PAL depends on mem, which depends on ds, so I think this stuff should stay in ds.
