### ISSUE TITLE
errno not always set correctly on failure

### ISSUE THREAD

**Issue by ronorton** [microsoft/snmalloc#461]
The malloc test contains some calls that are expected to fail such as attempts to allocate [very large chunks of memory](https://github.com/microsoft/snmalloc/blob/main/src/test/func/malloc/malloc.cc#L260). Currently these return `nullptr` but do not set `errno` to `ENOMEM` as required by the SUSv2 standard (at least according to the Linux manpage for `malloc`). Unfortunately `check_result` notices the incorrect `errno` but does not fail the test due to the `return` [here](https://github.com/microsoft/snmalloc/blob/main/src/test/func/malloc/malloc.cc#L30) so the test emits an error message but does not fail, for example:
```
realloc(0x40e60000(16384), 9223372036854775807)
Expected error: 12 but got 0
(test continues)
```

Note that there is a suspicious check for `realloc(-1)` in [override here](https://github.com/microsoft/snmalloc/blob/main/src/override/malloc.cc#L81) but I'm sure if this is related to the failure.

**Comment by ronorton** [comment]
I suppose this is tangentially related to #423 .

**Comment by mjp41** [comment]
So I am thinking of adding 
```
errno = ENOMEM;
```
on line 321:
https://github.com/microsoft/snmalloc/blob/af8ab2daf6455fa1f9d9daedeb65f6abc2d2d50e/src/pal/pal_posix.h#L298-L323

We should then review other `reserve` operations for specialised Pals such as 

https://github.com/microsoft/snmalloc/blob/af8ab2daf6455fa1f9d9daedeb65f6abc2d2d50e/src/pal/pal_bsd_aligned.h#L32-L55

and add the same to the `MAP_FAILED` case.

**Comment by mjp41** [comment]
We probably need to do something here too
https://github.com/microsoft/snmalloc/blob/af8ab2daf6455fa1f9d9daedeb65f6abc2d2d50e/src/mem/chunkallocator.h#L194-L198

**Comment by rmn30** [comment]
`mmap` should set errno on failure so setting it in `pal_posix.h` should not be required. Maybe the test is hitting the chunk allocator case?

**Comment by rmn30** [comment]
I can confirm that setting `errno` in `chunkallocator.h` fixes the test failure, but is that portable to non-posix PALs? Do we need a new PAL method?

**Comment by rmn30** [comment]
I think `errno` is specified by C / C++ standard so probably safe to just set it?
