### ISSUE TITLE
How to used snmalloc in VisualStudio 2017 for my CPP project

### ISSUE THREAD

**Issue by NewMai** [microsoft/snmalloc#525]
The document only show me how to use `snmalloc` with CMake:
https://github.com/microsoft/snmalloc/blob/main/docs/BUILDING.md#using-snmalloc-as-header-only-library

However, if my project is not based on CMake sytem, instead, it is base on `Visual Studion 2017`.
So, what should I do to replace the native `malloc` and `free` function with the snmalloc?

**Comment by mjp41** [comment]
@newMai thanks for your interest.  So replacing `malloc` and `free` is something we are looking into supporting (#480).  I believe if you follow the discussion in that thread you can replace `new` and `delete`, but not `malloc` and `free`.

You can link a static library that has the symbols `sn_malloc` and `sn_free`, which you could use to test for your scenario, but that would require rewriting.

**Comment by NewMai** [comment]
Thanks for your anwser @mjp41 ,
It works for `sn_xxx` function when I add the MACRO `SNMALLOC_STATIC_LIBRARY_PREFIX=sn_` to my VisualStudio projects by using `sn_malloc`, `sn_free` and `sn_memcpy` for `x64` platform.

However, when it comes to the `x86` platform, it dosen't work again and tells me the error message:

```sh
3>aux_new.obj : error LNK2019: 无法解析的外部符号 __imp__VirtualAlloc2FromApp@28，函数 "public: class snmalloc::CapPtr<void,struct snmalloc::capptr::bound<1,1,1> > __thiscall snmalloc::PagemapRegisterRange<class snmalloc::BasicPagemap<class snmalloc::BackendAllocator<class snmalloc::PALWindows,0>,class snmalloc::PALWindows,class snmalloc::FlatPagemap<14,class snmalloc::BackendAllocator<class snmalloc::PALWindows,0>::PageMapEntry,class snmalloc::PALWindows,0>,class snmalloc::BackendAllocator<class snmalloc::PALWindows,0>::PageMapEntry,0>,class snmalloc::PalRange<class snmalloc::PALWindows>,0>::alloc_range(unsigned int)" (?alloc_range@?$PagemapRegisterRange@V?$BasicPagemap@V?$BackendAllocator@VPALWindows@snmalloc@@$0A@@snmalloc@@VPALWindows@2@V?$FlatPagemap@$0O@VPageMapEntry@?$BackendAllocator@VPALWindows@snmalloc@@$0A@@snmalloc@@VPALWindows@3@$0A@@2@VPageMapEntry@12@$0A@@snmalloc@@V?$PalRange@VPALWindows@snmalloc@@@2@$0A@@snmalloc@@QAE?AV?$CapPtr@XU?$bound@$00$00$00@capptr@snmalloc@@@2@I@Z) 中引用了该符号
3>F:\tmp\test_malloc\test_snmalloc\build\Debug32\test_snmalloc.exe : fatal error LNK1120: 1 个无法解析的外部命令
```

**Comment by NewMai** [comment]
Great!
Really thanks for your help!
When adding the `mincore.lib` to addtional dependencies of the linker, it works.
It works for both `x32` and `x64` now!

**Comment by NewMai** [comment]
I am sorry to bother you again.
I have another question:
Dose the `snmalloc` support dynamic-build on `Windows` platform?
In another word, can we build the `snmalloc` as a `dll` module and use it in VisualStudio Project?

I saw the following config in `CMakeLists.txt`:
```CMake
  if(NOT WIN32)
    add_shim(snmallocshim SHARED ${SHIM_FILES})
    add_shim(snmallocshim-checks-memcpy-only SHARED ${SHIM_FILES} ${SHIM_FILES_MEMCPY})
    add_shim(snmallocshim-checks SHARED ${SHIM_FILES} ${SHIM_FILES_MEMCPY})
    target_compile_definitions(snmallocshim-checks PRIVATE SNMALLOC_CHECK_CLIENT)
  endif()
``` 
So, the dynamic module is only support in Unix-like platform?

**Comment by mjp41** [comment]
It is not something we have really considered.  We build the .so on Linux as that is how we intercept malloc/free on that platform.  On Windows the intercept is harder, and we haven't done that work.

I don't see why you couldn't build a .dll of the library which exposed the sn_malloc, etc. symbols.  I would not recommend unloading the dll as we have not considered how to do that.

@davidchisnall any additional thoughts?

**Comment by NewMai** [comment]
Ok, thanks anyway.

**Comment by mjp41** [comment]
Sorry, we don't regularly test on VS2017 as it was removed from CI.  I have a machine with it still installed, so I can take a look.   But the code is using C++17 features, so VS2017 might be struggling with that.

**Comment by mjp41** [comment]
> VS2017 also support `c++17` features. And, the usage of the docs is also based on `VS2017`: https://github.com/microsoft/snmalloc/blob/main/docs/BUILDING.md

Good point, I think we should update the docs to VS2019 as that is in used in CI.  Thanks for pointing it out.
