### ISSUE TITLE
Missing defines on systems with kernel < 4.X

### ISSUE THREAD

**Issue by mfelsche** [microsoft/snmalloc#544]
## Description
We are running into trouble with centos 7 based builds of snmalloc. ( [Dockerimage](https://hub.docker.com/layers/centos/library/centos/centos7.9.2009/images/sha256-8faead07bd1d5fdd17414a1759eae004da5daa9575a846f4730f44dec0f47843) )

We do have to support such an old system for the time being (don't ask), you might not want to support it, which i totally understand.
The system is based on gcc 9, kernel 3.10.0 and libraries, which is all horribly outdated.

Our build system gives the following error:

```
...
 /cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.3.1/snmalloc/src/snmalloc/override/../global/../backend/../backend_helpers/../mem/../ds/../pal/pal_linux.h: In static member function 'static void snmalloc::PALLinux::notify_not_using(void*, size_t)':
  /cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.3.1/snmalloc/src/snmalloc/override/../global/../backend/../backend_helpers/../mem/../ds/../pal/pal_linux.h:111:24: error: 'MADV_FREE' was not declared in this scope; did you mean 'MADV_REMOVE'?
    111 |       madvise(p, size, MADV_FREE);
        |                        ^~~~~~~~~
        |                        MADV_REMOVE
  /cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.3.1/snmalloc/src/snmalloc/override/../global/../backend/../backend_helpers/../mem/../ds/../pal/pal_linux.h: In static member function 'static uint64_t snmalloc::PALLinux::get_entropy64()':
  /cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.3.1/snmalloc/src/snmalloc/override/../global/../backend/../backend_helpers/../mem/../ds/../pal/pal_linux.h:180:57: error: 'GRND_NONBLOCK' was not declared in this scope; did you mean 'O_NONBLOCK'?
    180 |           ret = syscall(SYS_getrandom, current, length, GRND_NONBLOCK);
        |                                                         ^~~~~~~~~~~~~
        |                                                         O_NONBLOCK
  gmake[3]: *** [CMakeFiles/snmallocshim-rust.dir/src/snmalloc/override/rust.cc.o] Error 1
```

## Possible Solutions

On those old systems we do have `GRND_NONBLOCK` etc. defined in `/usr/include/linux/random.h`, i do think this include is missing (maybe guarded by a check if `GRND_NONBLOCK` is defined).

`MADV_FREE` is only available since linux 4.5. Should we fallback to `MADV_REMOVE` for systems where `MADV_FREE` is not defined?

I will happily provide those fixes if you deem them good enough or maybe you have another idea?

**Comment by mjp41** [comment]
So `MADV_FREE` could fall back to `MADV_DONTNEED`.

I am happy for a small amount of `ifdef` magic to handle this.  Overall, I can't promise I won't break things in the future, as this won't be tested in CI.  But the PAL tends not to change much, so I think it shouldn't be too bad.
