### ISSUE TITLE
snmalloc CI for Morello still uses github-act-runner 0.4.0 - GitHub Action Protocol Breaking July 31, 2023

### ISSUE THREAD

**Issue by ChristopherHX** [microsoft/snmalloc#625]
I want to raise awareness, that your morello ci is still using a github-act-runner below version < 0.6.3 and therfore will most likely break once the feature toggle is enabled server side. (This is the first time that all 0.0 - 0.5 releases of github-act-runner become useless on `github.com`, GHES has more time)

- Subscribe https://github.com/ChristopherHX/github-act-runner/issues/96 for updates
- https://github.blog/changelog/2023-01-31-github-actions-job-summary-updates/
- https://github.com/actions/runner/issues/886#issuecomment-1564345968
- The new protocol has been implemented in github-act-runner 0.6.3 without tests, but 0.4.0 cannot handle it.

_Until the breaking change is rolled out starting with July 31, 2023 it is unknown how the latest release (0.6.3) of github-act-runner is affected._

**Comment by nwf-msr** [comment]
Thanks for reaching out (and for `github-act-runner` in general)!  I've subscribed to the issue, moved our runners over to 0.6.3, and made a note to watch things at the end of the month.
