### ISSUE TITLE
mallocx and rallocx don't handle alignment

### ISSUE THREAD

**Issue by brooksdavis** [microsoft/snmalloc#649]
The comments for these jemalloc compatibility functions mention alignment, but the implementations don't parse the flags to implement it.

I noticed this because I'd modeled mallocx/rallocx implementation for the malloc revocation shim (mrs) in CheriBSD on the snmalloc implementations and then got this user report: https://github.com/CTSRD-CHERI/cheribsd/issues/1964

**Comment by mjp41** [comment]
So I am a bit confused: 
https://github.com/microsoft/snmalloc/blob/3c3739ddafa384da5c89984ec765a22af4d876a5/src/snmalloc/override/jemalloc_compat.cc#L252-L253
and
https://github.com/microsoft/snmalloc/blob/3c3739ddafa384da5c89984ec765a22af4d876a5/src/snmalloc/override/jemalloc_compat.cc#L270-L271
Seem to modify the size based on the alignment request.

So `snmalloc` has a very specific characteristic that any size will be aligned by the largest power of two which divides it.  For example,
```
480 = 32 * 3 * 5
```
So 480 would be guaranteed to be 32 byte aligned.  This independent of the chosen size classes, which could lead to more alignment.  This means that we don't treat alignment at all specially, most allocators have to add lots of code to the aligned case.  We just need a couple of instructions to round up to the alignment, and then the object is guaranteed to be aligned.

Have you replicated the problem with snmalloc?

**Comment by brooksdavis** [comment]
I see. I misread the code. Sorry for the noise.
