### ISSUE TITLE
Is it possible to make `snmalloc` freestanding?

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#670]
I know the build is actually free of STL linkage. However, snmalloc is not freestanding buildable because of the following:

https://github.com/microsoft/snmalloc/blob/6af38acd94d401313b7237bb7c2df5e662e135cf/src/snmalloc/ds_core/redblacktree.h#L6

Could we include the `<string>` header conditionally?

**Comment by mjp41** [comment]
Could you explain a bit more what is needed to make this freestanding?  If you could give a situation for use, and some build process that I can check this fits into that would be great.

**Comment by SchrodingerZhu** [comment]
My initial idea was to provide snmalloc to [llvm-libc](https://github.com/llvm/llvm-project/tree/main/libc) as an alternative allocator solution.

TO begin with, I think you can try compile `snmalloc` with `-ffreestanding`. I guess after the removal of `<string>, this is already doable.

**Comment by mjp41** [comment]
Compiling with `-ffreestanding` works as far as I can tell.
