### ISSUE TITLE
Sets `_HAS_EXCEPTIONS=0` globally

### ISSUE THREAD

**Issue by Kyuuhachi** [microsoft/snmalloc#701]
snmalloc has `target_compile_definitions(snmalloc INTERFACE -D_HAS_EXCEPTIONS=0)`, which seems to set that flag on all downstream consumers. This causes some rather strange issues in programs that use exceptions. Is this intentional? 

https://github.com/microsoft/snmalloc/blob/d6ad197d3c8452cd4d2548813e0b88a333ce11d6/CMakeLists.txt#L297

**Comment by mjp41** [comment]
I think that should be fixed.  I think it was so the various libraries we build do not have to support exceptions, and thus can be more efficiently compiled.  We should move that to just apply to the built libraries.

Probably moving it here would make sense:
https://github.com/microsoft/snmalloc/blob/d6ad197d3c8452cd4d2548813e0b88a333ce11d6/CMakeLists.txt#L431


@davidchisnall sounds sensible to you?

**Comment by mjp41** [comment]
Closed by #707.
