### ISSUE TITLE
Update BUILDING.md

### ISSUE THREAD

**Issue by NeilMonday** [microsoft/snmalloc#704]
Hello snmalloc developers. I was going through the build in my project and saw a couple of things that might need updating.

First, it looks like Visual Studio 15 aligns with 2017, not 2019.

It appears this style of generator name "Visual Studio 15 2019 Win64" are for compatibility with CMake versions before 3.1 which was around 2014. In modern CMake, the Visual Studio generator is specified like so:

cmake -G "Visual Studio 15 2017" -A Win32
cmake -G "Visual Studio 15 2017" -A x64
cmake -G "Visual Studio 15 2017" -A ARM
cmake -G "Visual Studio 15 2017" -A ARM64

Since you mention VS 2022 being used in CI regularly, it seems like that should be the generator used in the doc.

The path to malloc.cc and new.cc seem incorrect. Maybe it changed overtime and wasn't updated in the doc.

**Comment by mjp41** [comment]
Closed by #705
