### ISSUE TITLE
Is `TrivialInitAtomic` being used?

### ISSUE THREAD

**Issue by SchrodingerZhu** [microsoft/snmalloc#709]
I found the `TrivialInitAtomic` is a bit problematic. 

- First, with `atomic_ref`, one should align the value object to `std::atomic_ref<T>::required_alignment`, which is not enforced in our implementation.
- ~~Second, `compare_exchange` in `atomic_ref` incurs extra overhead if `std::has_unique_object_representations_v<T>` does not hold. e.g. T has padding.~~

Is this data structure being used? I don't see any reference to it. One would probably want something like the following or use https://en.cppreference.com/w/cpp/utility/launder (or https://en.cppreference.com/w/cpp/memory/start_lifetime_as) to do type punning instead.

```c++
#ifdef __cpp_lib_atomic_ref
    // If the object does not have a unique object representation, the
    // cmpxchg operation is implemented using a busy loop. We fallback to
    // std::atomic in this case.
    template<bool IsUnique>
    struct AtomicImpl;

    template<>
    struct AtomicImpl<true>
    {
      using Val = T;
      using Ref = std::atomic_ref<T>;
      static constexpr size_t ALIGNMENT = Ref::required_alignment;
    };

    template<>
    struct AtomicImpl<false>
    {
      using Val = std::atomic<T>;
      using Ref = std::atomic<T>&;
      static constexpr size_t ALIGNMENT = alignof(Val);
    };

    static constexpr bool IS_UNIQUE =
      std::has_unique_object_representations_v<T>;

    using Val = typename AtomicImpl<IS_UNIQUE>::Val;
    using Ref = typename AtomicImpl<IS_UNIQUE>::Ref;
    static constexpr size_t ALIGNMENT = AtomicImpl<IS_UNIQUE>::ALIGNMENT;
#else
    using Val = std::atomic<T>;
    using Ref = std::atomic<T>&;
    static constexpr size_t ALIGNMENT = alignof(Val);
#endif
```

**Comment by SchrodingerZhu** [comment]
I was wrong about the second point. Actually, I was misled by the `libc++` implementation as it is not yet standard-compliant. Per ISO C++20, `compare_exchange` examines equality on value representations of the object. Hence, if the object is padded, `compare_exchange` is non-wait-free busy loop. This applies to both `std::atomic` and `std::atomic_ref`. This is not yet effective with `clang/libc++` as `__builtin_clear_padding` is not yet implemented by `clang`.

**Comment by mjp41** [comment]
It doesn't look like it is used anymore.  It was written for an earlier version of the Pagemap that had some complex initialisation issues.  I think we could drop.  @nwf would that be okay with you?
