### ISSUE TITLE
debug_check_empty useless after message queue changes

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#79]
Bisecting reveals that eb4e28e8d0c9ee37096771728b90c5e364548e8b, while it does remove the special case, breaks tests like `func-memory` that expect to be able to test that there are no outstanding allocations, becuase every allocator will be nonempty, having message queue stubs in place.  The fix, I think, is to move the test for emptiness into the main loop, testing for emptiness between `alloc->message_queue().destroy()` and `alloc->init_message_queue()`; the count must be reset to zero at the top of the main loop.

**Comment by mjp41** [comment]
Thanks for reporting this. I see you have a commit in your fork to fix this. Have you managed to get the University to approve the CLA? If so, can you PR it in?

**Comment by nwf** [comment]
I have not, which is why I didn't open a PR.  Apparently the entire CTSRD project is stuck in legal limbo for reasons that escape me.

**Comment by mjp41** [comment]
Looking at this, I think there are more issues introduced by this change because of the allocator local free lists.  I will create some tests to more properly check this. And address these issues.

**Comment by mjp41** [comment]
Resolved by #84
