### ISSUE TITLE
func-fixed_region is not built correctly

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#81]
When running revions after e240dd279a0c40247abd1324604eb58be6cf620c with `-O2` and `USE_SNMALLOC_STATS` enabled and on a Linux amd64 box, `func-fixed_region-16` crashes (but `func-fixed_region-1` does not).  The tail of the output under `gdb` is

```
Allocated object 0x7fffea02b530
Allocated object 0x7fffea02b5a0
GlobalStats, DumpID, AllocatorID, Remote freed, Remote posted, Remote received, Superslab pop, Superslab push, Superslab fresh, Segments
BucketedStats, DumpID, AllocatorID, Size group, Size, Current count, Max count, Total Allocs, Current Slab bytes, Max Slab bytes, Total slab allocs, Average Slab Usage, Average wasted space

Program received signal SIGSEGV, Segmentation fault.
snmalloc::FlatPagemap<24ul, unsigned char>::get (p=140737119453312, this=<optimised out>)
    at /home/nwf20/cheri/mainline/snmalloc/src/override/../mem/pagemap.h:360
360	      return top[p >> SHIFT].load(std::memory_order_relaxed);

```

The backtrace is... well, fairly full of POSIX and C++ dragons:

```
#0  snmalloc::FlatPagemap<24ul, unsigned char>::get (p=140737119453312, this=<optimised out>)
    at /home/nwf20/cheri/mainline/snmalloc/src/override/../mem/pagemap.h:360
#1  snmalloc::SuperslabMap<snmalloc::GlobalPagemap>::get (p=140737119453312, this=<optimised out>)
    at /home/nwf20/cheri/mainline/snmalloc/src/override/../mem/alloc.h:135
#2  snmalloc::Allocator<snmalloc::MemoryProviderStateMixin<snmalloc::PALLinux>, snmalloc::SuperslabMap<snmalloc::GlobalPagemap>, true, &snmalloc::lazy_replacement>::dealloc (this=0x7fffe8004000, p=0x7fffea030080)
    at /home/nwf20/cheri/mainline/snmalloc/src/override/../mem/alloc.h:465
#3  operator delete (p=0x7fffea030080) at /home/nwf20/cheri/mainline/snmalloc/src/override/new.cc:41
#4  0x0000000000403451 in __gnu_cxx::new_allocator<char>::deallocate (__p=0x7fffea030080 "Average wasted space", 
    this=<optimised out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ext/new_allocator.h:125
#5  std::allocator_traits<std::allocator<char> >::deallocate (__p=0x7fffea030080 "Average wasted space", __a=..., 
    __n=<optimised out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/alloc_traits.h:462
#6  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (this=<optimised out>, 
    __size=<optimised out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/basic_string.h:226
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=<optimised out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/basic_string.h:221
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=<optimised out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/basic_string.h:647
#9  snmalloc::AllocStats<75ul, 24ul>::print<snmalloc::Allocator<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >, snmalloc::SuperslabMap<snmalloc::GlobalPagemap>, true, &snmalloc::lazy_replacement> > (
    this=0x7fffffffb360, o=..., dumpid=0, allocatorid=0) at /home/nwf20/cheri/mainline/snmalloc/src/mem/allocstats.h:329
#10 0x000000000040225c in snmalloc::ThreadAllocExplicitTLSCleanup::print_stats ()
    at /home/nwf20/cheri/mainline/snmalloc/src/mem/threadalloc.h:259
#11 0x00007ffff6ec9041 in __run_exit_handlers (status=0, listp=0x7ffff7271718 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#12 0x00007ffff6ec913a in __GI_exit (status=<optimised out>) at exit.c:139
#13 0x00007ffff6ea7b9e in __libc_start_main (main=0x400f50 <main()>, argc=1, argv=0x7fffffffe6b8, init=<optimised out>, 
    fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffe6a8) at ../csu/libc-start.c:344
#14 0x0000000000400e4a in _start ()
```

We're printing out statistics from the `atexit()` handler (frame 10) and we're trying to run the C++ string destructor (frame 8), which is being routed through the snmalloc-intercepted `operator delete` (frame 3).  This allocator believes its memory provider's PAL to be `PALLinux`, and the `GlobalPagemap` seems to be a `FlatPagemap`, looking at frame 1.

What's going on is that in this test `fixed_region.cc` contains `#define OPEN_ENCLAVE` thereby making `Pal` `PALPlainMixin<PALOpenEnclave>`  and `DefaultPal` `PALLinux`.  Thus, when the test calls `ThreadAlloc::get()`, the global allocator type is going to be one with the OpenEnclave PAL.  So far so good, I suppose.  **However**, `src/override/new.cc` is built separately, and therefore does not see `OPEN_ENCLAVE` being asserted, and so, horrors, it believes that `Pal` and `DefaultPal` are both `PALLinux`, and so will build code assuming that allocators use flat page maps, even when, as we have just observed above, the global allocator is initialized by someone else and has the wrong type.

I think that `func-fixed_region` should be changed so that both its main file and `new.cc` are in agreement that `PALOpenEnclave` is the correct thing to build all allocators around.

`func-two_alloc_types` doesn't trip over this perhaps because it happens that its `main.cc` does not define `OPEN_ENCLAVE` and so will construct the global pool around `PALLinux`, in agreement with `new.cc` and, moreover, the name mangling ensures that `alloc1` and `alloc2` have different `ThreadAlloc` pools.  The calls to `snmalloc_pagemap_global_get` do not ensure that the two allocators' pagemaps have equal layout (and in fact, they don't): the pagemap config is overwritten prior to the assert within this function, which therefore always passes.  Perhaps what was meant was something like
```
  SNMALLOC_EXPORT void* SNMALLOC_NAME_MANGLE(snmalloc_pagemap_global_get)(
    PagemapConfig const** config)
  {
    if (config)
    {
      assert( *config == NULL ||
        decltype(snmalloc::global_pagemap)::cast_to_pagemap(
          &snmalloc::global_pagemap, *config) == &snmalloc::global_pagemap);
      *config = &decltype(snmalloc::global_pagemap)::config;
    }
    return &snmalloc::global_pagemap;
  }
```
which does not pass in `func-two_alloc_types` (with `c = NULL;` added before the first call so that it's initialized).

**Comment by mjp41** [comment]
Resolved by #84 and #86 .
