### ISSUE TITLE
Lazy TLS initialization breaks stats counting

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#82]
Bisection reveals that b8a5d7fca96fd442eb74df8db59666bd1704696c breaks the idea that stat counters don't go negative.  In particular, adding `assert(sizeclass[sc].count.current > 0);` to `sizeclass_dealloc` (and applying the fix for #79) will cause at least `func-malloc` to fail on that commit and  after.  The problem is that `small_alloc`'s call to `stats().sizeclass_alloc` happen before the check that we're on the fast path, and so apply to the stub global allocator's stat structure.  This does not appear to be a problem in `medium_alloc` or `large_alloc`, as the replacement path will have tail-called before attempting to update the stub's stats structure.

**Comment by mjp41** [comment]
Thanks for reporting this.  I see you have a commit in your fork to fix this.  Have you managed to get the University to approve the CLA?  If so, can you PR it in?

**Comment by mjp41** [comment]
Resolved by #84
