### ISSUE TITLE
Build more efficient statistics for Release builds

### ISSUE THREAD

**Issue by mjp41** [microsoft/snmalloc#83]
The statistics code has not been maintained during several refactors. This needs addressing.

* Tests need adding to check the statistics are correct for the amount of allocations and deallocations.
* All functional tests should build with statistics switched on.
* Fast path needs to maintain statistics approximately.  Whenever a free list is grabbed, then we will consider all the elements allocated in the statistics.  To regain accurate statistics, we will need to empty the allocator local free lists.

Once addressed, we should be able to close #79 #80 #82.

**Comment by mjp41** [comment]
The basics are now correct, but we need to add more tests, and potentially build more efficient statistics for Release builds.

**Comment by achamayou** [comment]
@mjp41 where can one find those statistics? I'd like to try plugging them into https://github.com/jumaffre/cimetrics, if that's ok.

**Comment by mjp41** [comment]
You can build with `-DUSE_SNMALLOC_STATS` this will print the stats at exit at the moment.  I haven't really worked on the API here as I didn't want to spend time until someone said what they wanted.

Also, -DUSE_SNMALLOC_STATS is quite expensive, so we might want to implement something more optimal.

**Comment by mjp41** [comment]
The old statistics code has been remove with 0.6.0 and the lightweight statistics introduced for OE are all we currently provide.
