### ISSUE TITLE
Statistics underflow

### ISSUE THREAD

**Issue by nwf** [microsoft/snmalloc#98]
https://github.com/microsoft/snmalloc/commit/c2799f6ec8ed43b87d520d58ff7c52e57a28a2fb#diff-a8ebb8308aa3e85926e29a0e7e02f444R913 calls `dealloc` on objects sourced from the free list.  This seems kind of dubious to me but at the very least causes the statistics counters to underflow, since it deallocates an object not accounted for.

**Comment by mjp41** [comment]
Good catch thanks.
